version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u181-jdk-stretch
    steps:
      - checkout
      - run: mvn clean test
      - store_test_results:
          path: target/surefire-reports
